# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='guest', max_length=200),
        ),
    ]
