# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komentor', '0002_auto_20170501_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
